version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  tracker:
    build: .
    container_name: tracker
    environment:
      - RPC_URL=${RPC_URL}
      - MONGO_URI=mongodb://mongo:27017/eth_deposit_tracker
      - ETH_BLOCK_FROM=${ETH_BLOCK_FROM}
    depends_on:
      - mongo

volumes:
  mongo-data:
